### ISSUE TITLE
Configurable/discoverable alerts

### ISSUE THREAD

**Issue by ScottGuymer** [philips-labs/variant#4]
In Prometheus operator you can deploy new alerts with the use of a CRD and the operator will pick them up and apply them to the prom config.

How could we facilitate the same thing in CF?

**Comment by loafoe** [comment]
We should probably come up with a set of annotations that describe alerts and then scrape them similar to the exporter endpoints. I haven't delved into alerts yet, but we'll probably also want to incorporate `alertmanager` for de-duping and external notificatio. This should be covered in the thanos module, or perhaps as a standalone module.

**Comment by ScottGuymer** [comment]
alerts could get pretty long. Is there a limit on the length of an annotation? Might we have to use separata annotations per rule?

**Comment by loafoe** [comment]
there is a limit of `5000` bytes yes, which should be more than enough to capture a single alert

**Comment by ScottGuymer** [comment]
Seems reasonable.

This alert

```
  - alert: PrometheusJobMissing
    expr: absent(up{job="prometheus"})
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Prometheus job missing (instance {{ $labels.instance }})
      description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

as a base64 string is just over 400 chars..
